version: '3'

services:
  rabbit_mq:
    image: rabbitmq:management-alpine
    restart: always
    container_name: rabbit_mq
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  producer:
    build: proxy_producer
    container_name: proxy_producer
    restart: always
    depends_on:
      - rabbit_mq
      - database
    environment:
      AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
      DB_HOST: database
      DB_NAME: 'homestead'
      DB_PORT: 5432
      DB_USER: 'user'
      DB_PASS: 'pass'
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 100M

  proxy-checker:
    build: proxy_checker
    restart: always
    depends_on:
      - rabbit_mq
      - database
    environment:
      AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 30M
        reservations:
          memory: 100M

  database:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=homestead
    volumes:
      - pg_project:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 200M

volumes:
  pg_project:
  rabbit_mqdata:
    driver: local
